#!/bin/bash
cat << 'EOF'
   ____ ___    ______ ____    _____            _                                      _   
  / ___|_ _|  / / ___|  _ \  | ____|_ ____   _(_)_ __ ___  _ __  _ __ ___   ___ _ __ | |_ 
 | |    | |  / / |   | | | | |  _| | '_ \ \ / / | '__/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __|
 | |___ | | / /| |___| |_| | | |___| | | \ V /| | | | (_) | | | | | | | | |  __/ | | | |_ 
  \____|___/_/  \____|____/  |_____|_| |_|\_/ |_|_|  \___/|_| |_|_| |_| |_|\___|_| |_|\__|
                                                                                          
EOF
echo "CI_COMMIT_AUTHOR: $CI_COMMIT_AUTHOR"
echo "CI_COMMIT_BRANCH: $CI_COMMIT_BRANCH"
echo "CI_COMMIT_MESSAGE: $CI_COMMIT_MESSAGE"
echo "CI_COMMIT_REF_NAME: $CI_COMMIT_REF_NAME"
echo "CI_COMMIT_REF_SLUG: $CI_COMMIT_REF_SLUG"
echo "CI_COMMIT_SHA: $CI_COMMIT_SHA"
echo "CI_COMMIT_SHORT_SHA: $CI_COMMIT_SHORT_SHA"
echo "CI_COMMIT_TIMESTAMP: $CI_COMMIT_TIMESTAMP"
echo "CI_COMMIT_TITLE: $CI_COMMIT_TITLE"
echo "CI_JOB_ARTIFACTS: $CI_JOB_ARTIFACTS"
echo "CI_JOB_ARTIFACTS_DIR: $CI_JOB_ARTIFACTS_DIR"
echo "CI_JOB_ARTIFACTS_EXPIRATION: $CI_JOB_ARTIFACTS_EXPIRATION"
echo "CI_JOB_ARTIFACTS_URL: $CI_JOB_ARTIFACTS_URL"
echo "CI_JOB_DURATION: $CI_JOB_DURATION"
echo "CI_JOB_ID: $CI_JOB_ID"
echo "CI_JOB_MANUAL: $CI_JOB_MANUAL"
echo "CI_JOB_NAME: $CI_JOB_NAME"
echo "CI_JOB_STAGE: $CI_JOB_STAGE"
echo "CI_JOB_STARTED_AT: $CI_JOB_STARTED_AT"
echo "CI_JOB_STOPPED_AT: $CI_JOB_STOPPED_AT"
echo "CI_JOB_TRIGGERED: $CI_JOB_TRIGGERED"
echo "CI_JOB_URL: $CI_JOB_URL"
echo "CI_PIPELINE_ID: $CI_PIPELINE_ID"
echo "CI_PIPELINE_URL: $CI_PIPELINE_URL"
echo "CI_PROJECT_DIR: $CI_PROJECT_DIR"
echo "CI_PROJECT_ID: $CI_PROJECT_ID"
echo "CI_PROJECT_NAME: $CI_PROJECT_NAME"
echo "CI_PROJECT_TITLE: $CI_PROJECT_TITLE"
echo "CI_PROJECT_URL: $CI_PROJECT_URL"
echo "CI_SERVER_HOST: $CI_SERVER_HOST"
echo "CI_SERVER_NAME: $CI_SERVER_NAME"
echo "CI_SERVER_PORT: $CI_SERVER_PORT"
echo "CI_SERVER_PROTOCOL: $CI_SERVER_PROTOCOL"
echo "CI_SERVER_REVISION: $CI_SERVER_REVISION"
echo "CI_SERVER_URL: $CI_SERVER_URL"
echo "CI_SERVER_VERSION: $CI_SERVER_VERSION"
echo "CI_SERVER_VERSION_MINOR: $CI_SERVER_VERSION_MINOR"
echo "GITLAB_USER_EMAIL: $GITLAB_USER_EMAIL"
echo "GITLAB_USER_ID: $GITLAB_USER_ID"
echo "GITLAB_USER_LOGIN: $GITLAB_USER_LOGIN"
echo "GITLAB_USER_NAME: $GITLAB_USER_NAME"
echo "GITLAB_USER_URL: $GITLAB_USER_URL"
echo "--------------------------------------------------------------------------------"
echo "Current PWD: $PWD"
echo "Current USER: $USER"
echo "Current HOME: $HOME"
echo "Current SHELL: $SHELL"
echo "Current PATH: $PATH"
echo "Current LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "Current LANG: $LANG"
echo "Current LANGUAGE: $LANGUAGE"
echo "Current LC_ALL: $LC_ALL"
echo "--------------------------------------------------------------------------------"
echo "done."
